# fly.toml file generated for f1abeez-bot on 2022-08-29T17:15:19+02:00

app = "f1abeez-bot"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true