on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: npm
      - name: Install
        run: npm i
      - name: Building Typescript
        uses: FuLagann/tsc-build-push@v1
        with:
          user-name: "Jakub Hašek"
          user-email: "hasek.kuba@hotmail.cz"
          message: "Build: action"
