name: Deploy
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: deploy # make sure the notification is sent AFTER the jobs you want included have completed
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GITHUB FELLA"
          avatar-url: "https://octodex.github.com/images/manufacturetocat.png"
          title: "${{ github.workflow }}: {{STATUS}}"
          include-details: "true"
          color-success: "#4287f5"
          color-failure: "eb4034"
          color-cancelled: "0x42daf5"
